# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=siamese
      - POSTGRES_PASSWORD=siamese
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - catalogdb_volume:/var/lib/postgresql/data   

  catalog.api:
    container_name: catalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Dvelopment
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1212312121
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=siamese;Password=siamese
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6050:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ${APPDATA}/Roaming/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Roaming/ASP.NET/Https:/home/app/.aspnet/https:ro