# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  catalogdb:
    image: postgres

  catalog.api:
    image: catalog-api
    build: 
      context: .
      dockerfile: src\Services\Catalog\Catalog.API\Dockerfile



volumes:
  catalogdb_volume: